apiVersion: apps/v1
kind: Deployment
metadata:
  name: v75-bmw
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: v75-bmw
  template:
    metadata:
      labels:
        app: v75-bmw
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
